apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: federated
    federated-prometheus: "true"
  name: prometheus-federated
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
    path: /federate
    honorLabels: true
    params:
      'match[]':
        - up
        - server_api_get_admin_health
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      prometheus: federated
