kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-exocortex-rules
  namespace: monitoring
  labels:
    role: alert-rules
    prometheus: k8s
data:
  exocortex.rules.yaml: |+
    groups:
    - name: ./exocortex.rules
      rules:
      - record: job_cronjob:kube_job_status_start_time:max
        expr: |
          label_replace(
            label_replace(
              max(
                kube_job_status_start_time
                * ON(job) GROUP_RIGHT()
                kube_job_labels{label_cronjob!=""}
              ) BY (job, label_cronjob)
              == ON(label_cronjob) GROUP_LEFT()
              max(
                kube_job_status_start_time
                * ON(job) GROUP_RIGHT()
                kube_job_labels{label_cronjob!=""}
              ) BY (label_cronjob),
              "job", "$1", "job", "(.+)"),
            "cronjob", "$1", "label_cronjob", "(.+)")
      - record: job_cronjob:kube_job_status_failed:sum
        expr: |
          clamp_max(
            job_cronjob:kube_job_status_start_time:max,
          1)
          * ON(job) GROUP_LEFT()
          label_replace(
            label_replace(
              (kube_job_status_failed != 0),
              "job", "$1", "exported_job", "(.+)"),
            "cronjob", "$1", "label_cronjob", "(.+)")
