apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-serv093
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /srv/monitoring/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
          - serv093.threehub.net

